Backend: Catapult 
KerasJson: ternary_tanh.json
KerasH5: ternary_tanh_weights.h5
OutputDir: my-Catapult-test
ProjectName:  ternary_tanh 
XilinxPart: xcku115-flvb2104-2-i
Part: xcku115-flvb2104-2-i
ClockPeriod: 5

IOType : io_parallel
HLSConfig:
  Model:
    Precision: ap_fixed<16, 6>
    ReuseFactor: 1
    Strategy: Latency
